# Generated by Django 4.2.11 on 2025-05-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
