# Generated by Django 4.2.11 on 2025-06-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_salesinvoice_amount_paid_salesinvoice_due_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
