# Generated by Django 4.2.11 on 2025-05-13 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='po_number',
        ),
    ]
