# Generated by Django 4.2.11 on 2025-06-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_salesinvoice_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
