# Generated by Django 4.2.11 on 2025-05-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_product_po_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='remark',
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
