# Generated by Django 4.2.11 on 2025-06-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_purchaseinvoice_date_alter_salesinvoice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='date',
            field=models.DateField(),
        ),
    ]
