# Generated by Django 4.2.11 on 2025-05-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_purchaseinvoice_remark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
