# Generated by Django 4.2.11 on 2025-05-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventory_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='address',
            field=models.TextField(default=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='name',
            field=models.CharField(default=6, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='phone',
            field=models.CharField(default=6, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='source_of_purchase',
            field=models.CharField(default=6, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='voucher_no',
            field=models.CharField(default=6, max_length=50),
            preserve_default=False,
        ),
    ]
