# Generated by Django 4.2.11 on 2025-05-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_purchaseinvoice_address_purchaseinvoice_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesinvoice',
            name='tt',
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='address',
            field=models.TextField(default=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='name',
            field=models.CharField(default=6, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='phone',
            field=models.CharField(default=6, max_length=15),
            preserve_default=False,
        ),
    ]
