# Generated by Django 4.2.11 on 2025-05-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_salesinvoice_tt_salesinvoice_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitem',
            name='it_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
